# Generated by Django 4.1.5 on 2023-02-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_signup_address_remove_signup_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='first_name',
            new_name='name',
        ),
    ]
